### ISSUE TITLE
Fix colour issues in UI

### ISSUE THREAD

**Issue by Aquarinte** [CS2103JAN2018-F14-B2/main#178]
- [x] **Hard to see button label in light theme**
![image](https://user-images.githubusercontent.com/15257617/38457377-3e2380aa-3ac2-11e8-8e00-7d541f9ebda7.png)

- [ ]  **Difficult to see appt details in dark theme**
![image](https://user-images.githubusercontent.com/15257617/38457373-2700ff1a-3ac2-11e8-97df-63118e7244f5.png)

- [x]  **Weird dark grey area**
![image](https://user-images.githubusercontent.com/15257617/38463323-d8d42b28-3b2a-11e8-9830-92c5765c72f5.png)

#63

**Comment by Robert-Peng** [comment]
The button label I've already updated in previous PRs, did you pull from team Repo?

**Comment by Aquarinte** [comment]
@Robert-Peng  Yes I've pulled from team repo. I noticed the button issue in light theme ytd using the latest updates. Did you change the css for light team in ur previous PR?
