### ISSUE TITLE
Remove select command and all related code/functions

### ISSUE THREAD

**Issue by Aquarinte** [CS2103JAN2018-F14-B2/main#180]
- Both person cards and petpatient cards should not be clickable

- Remove all related events e.g. JumpToListRequestEvent, PetPatientPatientSelectionChangedEvent etc
- Remove BrowserPanel and all related usages/methods
- Remove related methods from all JUnit tests e.g. AddCommandSystemTest, DeleteCommandSystemTest, EditCommandSystemTest etc

**Comment by wynonaK** [comment]
Will not be doing by v1.5
