### ISSUE TITLE
Bug in regex for add, edit, delete, find commands

### ISSUE THREAD

**Issue by Aquarinte** [CS2103JAN2018-F14-B2/main#208]
Causes inaccurate error messages e.g. 

![image](https://user-images.githubusercontent.com/15257617/38628946-3cd4f53c-3de5-11e8-807a-c2b65bb28439.png)

![image](https://user-images.githubusercontent.com/15257617/38628987-599d94ee-3de5-11e8-9d5e-bc86d90f3a49.png)

**Should throw "invalid command format!" error message.**

**Comment by Aquarinte** [comment]
- **Partial fix** for **add**
- **Fix** for **edit, find, delete**
![image](https://user-images.githubusercontent.com/15257617/38629075-9cd358e8-3de5-11e8-9eb6-bc2c101909ca.png)

**Comment by wynonaK** [comment]
not a bug, it is just being read in as additional parameters. 
The way argmultimap works for prefixes is also similar, theres no need to consider this a bug.
