### ISSUE TITLE
Several Bugs in Add Command

### ISSUE THREAD

**Issue by chialejing** [CS2103JAN2018-F14-B2/main#81]
These are the bugs relating to logic that I have found when testing Medeina's storage functions. I have yet to figure out the sources of these bugs as I am not that familiar with the logic part of AddComamnd and was also more focused on getting storage and conversion from XML to Objects and vice versa to work. Please help to resolve if you know where the sources of error are at.

- After typing the following invalid command, no errors pop up, no response from the application whatsoever - should show "NRIC invalid" or some other message (UX + logic problem). But pet does not get added to database (as expected).
`add -p n/Jay s/Cat b/Persian c/Black bt/AB -o S3948923489234`

- Somehow calls up "Person names should only contain alphanumeric characters and spaces, and it should not be blank" upon executing the following command. However, in `PetPatientName` class, the correct string has already been specified in `MESSAGE_PET_NAME_CONSTRAINTS`; uncertain why it will call `MESSAGE_NAME_CONSTRAINTS` from the `Person` class instead.
`add -p n/J@y s/Cat b/Persian c/Black bt/A -o S1234577A`

- Upon executing the following command, there is _no output telling the user that the appointment has been successfully added_ (i.e. command keyed in is not cleared; looks like as if nothing happened). However, if executed again, only then will the user know that the command has been successfully executed **previously** and the appointment has been added, since the output now shows that a duplicate appointment exists.
`add -a d/2018-12-30 12:30 r/nil t/checkup -o S7654321A -p Jay`

Refer to Issue #67 .

**Comment by Aquarinte** [comment]
These bugs are fixed in pull req #82

**Comment by Aquarinte** [comment]
Sorry, not all bugs were fixed. 2nd bug is related to #74.
