### ISSUE TITLE
Duration / End Time Field in Appointment

### ISSUE THREAD

**Issue by chialejing** [CS2103JAN2018-F14-B2/main#91]
- Will be good to have an end time field or at least duration for an appointment
- So that we ensure that users have ample time for an appointment
- Disallows the case where two appointments can be just 1 minute apart
- Alternatively we can have a blocks of time implementation: blocks of 15 / 30 mins are assigned instead

[_Discussion still in progress_]

**Comment by wynonaK** [comment]
WIll not be doing this by Medeina v1.5.
