### ISSUE TITLE
Owners do not have a pet patient name tied to them

### ISSUE THREAD

**Issue by wynonaK** [CS2103JAN2018-F14-B2/main#92]
Possible bug? 

During discussion we described that owners can have a List<PetPatientName> of pet patients, of which it can be null. Do we void this?

**Comment by Aquarinte** [comment]
Person object are independent. They can have no pet patients (becoz they may not be an owner, could be a medical supplies provider, or even a cremation service provider etc). So person objects do not need to be tied to pet patients objects, but pet patients must each be tied to 1 person object.

**Comment by wynonaK** [comment]
Closed as not an issue.
